//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_SignalR_SQLDependency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersChat
    {
        public System.Guid IDConnection { get; set; }
        public string loginName { get; set; }
    }
}
